### ISSUE TITLE
Scroll back to top when clicking on new chapter

### ISSUE THREAD

**Issue by ffd8** [micuat/hydra-book#1] opened 2021-04-24 12:40 UTC
@micuat this is an awesome resource, thanks for making! I noticed while browsing that if I'm scrolled a ways into one section, clicking on the next section– still leaves me scrolled down a ways into it = kinda confusing. Seems like some chapters, ie. `colors`, does scroll back to top, while others, `javascript` + `performing`, don't. Guessing was intended to do but missed on some sections?

**Comment by micuat** [comment] 2021-04-24 13:00
good point - I found this "problem" in docsify. There must be a flag or something to default to jump to the top, I will check later!

**Comment by micuat** [comment] 2021-04-24 13:13
ok I think the problem is that in the sidebar I set id anchors (e.g., `textures#textures`) but the performing chapter has wrong heading name (the file/url is `performing` but id is `performing-with-hydra`) and that's where the problem comes from. I will fix it now but not sure if there's a better way so I don't have to specify ids manually (and defaults to the top) - perhaps I can inject javascript to docsify

**Comment by micuat** [comment] 2021-04-24 13:21
oh I didn't know if you mention issue in commit it closes it .... ??? I reopen because I want to make it automated somehow with a script to default to top

edit: https://saraford.net/2017/02/15/how-to-automatically-close-issues-when-you-push-a-commit-to-github-046/
ok yes I wrote "temp fix" 😂

**Comment by ffd8** [comment] 2021-04-24 13:28
woohoo - just loaded online version and functions perfect! thx for coffeebreak instafix!

**Comment by micuat** [comment] 2021-04-24 13:53
ok Interestingly sidebar doesn't properly load on firefox / auto2top doesn't work on firefox while everything is fine on chrome.

**Comment by micuat** [comment] 2021-04-24 13:57
tested on windows10/firefox it works fine. Something specific to Ubuntu/firefox. :( closing for now

**Closed as completed by micuat** 2021-04-24 13:57 UTC
Labels: don't blame me, I hate javascript
